import './libs/luxon';
import './utils/class-to-data-attr';
import './utils/global-methods';
import './components/_bp-components-object';
import './utils/ie-checker';
//import './components/gsk-global-gtm-ga-tagging';
import './components/exit-notification';
// import './libs/hammer'
import './libs/slugify';
// import './libs/jquery.ui.touch-punch'

//import './utils/clickable-box';
//import './utils/gtm-tracker';
import './utils/in-viewport';
import './utils/interval';

//import './components/gigya-date-of-birth-checker';
import './components/accordion-block';
import './components/country-selector';
import './components/search-input';
import './components/navigation';
import './components/stickymenu';
//import './components/youtube-video';
//import './components/gatagging'
import './components/filter';
import './components/carousels';
//import './components/youtube-videos-v2';
import './utils/iefixes';
import './components/accordion-preselect-hash';
//import './components/video-background';
//import './components/bp-paralax';
import './components/anchor-box';
import './components/fullbox';
//import './components/table';
import './components/revtrax';
import './components/forms';
//import './components/bp-sharer';
import './components/popup-youtube-video';
//import './components/action-link';
//import './components/bp-video-player';
//import './components/bp-font-resizer';
//import './components/bp-share-container';
import './components/bp-tab-indexer-bp1';
//import './components/bp-content-loader';
//import './components/bp-toggler';
import './utils/switchable-image';
import './utils/product-filter';
//import './utils/youtube-video';
import './libs/lightslider';
import './brand/index';
